//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksLibrary.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Book
    {
        public int Book_Id { get; set; }

        [Required(ErrorMessage = "The field is required.")]
        public string ISBN { get; set; }

        [Required(ErrorMessage ="The field is required.")]
        [Display(Name = "Book Name")]
        public string Book_Name { get; set; }

        [Display(Name = "Author Id")]
        public int Author_Id { get; set; }

        [Required(ErrorMessage = "The field is required.")]
        [Display(Name = "Publication Date")]
        [DataType(DataType.Date)]
        public DateTime Publication_Date { get; set; }

        [Display(Name = "Category Id")]
        public int Category_Id { get; set; }

        [Required(ErrorMessage = "The field is required.")]
        public string Publisher { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Category Category { get; set; }
    }
}
