
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BooksLibrary.DomainModel.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Book
{

    public int Book_Id { get; set; }

    public string ISBN { get; set; }

    public string Book_Name { get; set; }

    public int Author_Id { get; set; }

    public Nullable<System.DateTime> Publication_Date { get; set; }

    public int Category_Id { get; set; }

    public string Publisher { get; set; }



    public virtual Author Author { get; set; }

    public virtual Category Category { get; set; }

}

}
